mutation CreateDemoData @transaction @auth(level: PUBLIC, insecureReason: "This mutation is used to seed the database with example data and is safe to expose to the public.") {
  user_insertMany(data: [
    {
      id: "550e8400-e29b-41d4-a716-446655440000",
      createdAt: "2024-03-15T12:00:00Z",
      email: "demouser1@example.com",
      firstName: "Demo",
      lastName: "User1",
      password: "password",
      phoneNumber: "123-456-7890",
      role: "customer"
    },
    {
      id: "550e8400-e29b-41d4-a716-446655440001",
      createdAt: "2024-03-15T12:00:00Z",
      email: "demouser2@example.com",
      firstName: "Demo",
      lastName: "User2",
      password: "password",
      phoneNumber: "987-654-3210",
      role: "employee"
    }
  ])
  service_insertMany(data: [
    {
      id: "650e8400-e29b-41d4-a716-446655440000",
      createdAt: "2024-03-15T12:00:00Z",
      description: "A haircut and style.",
      durationMinutes: 60,
      name: "Haircut",
      price: 50.00
    },
    {
      id: "650e8400-e29b-41d4-a716-446655440001",
      createdAt: "2024-03-15T12:00:00Z",
      description: "A manicure.",
      durationMinutes: 30,
      name: "Manicure",
      price: 30.00
    }
  ])
  employeeAvailability_insertMany(data: [
    {
      id: "750e8400-e29b-41d4-a716-446655440000",
      employeeId: "550e8400-e29b-41d4-a716-446655440001",
      breakTimes: "13:00-13:30",
      createdAt: "2024-03-15T12:00:00Z",
      dayOfWeek: "Monday",
      endTime: "17:00",
      startTime: "09:00"
    },
    {
      id: "750e8400-e29b-41d4-a716-446655440001",
      employeeId: "550e8400-e29b-41d4-a716-446655440001",
      breakTimes: "13:00-13:30",
      createdAt: "2024-03-15T12:00:00Z",
      dayOfWeek: "Tuesday",
      endTime: "17:00",
      startTime: "09:00"
    }
  ])
  appointment_insertMany(data: [
    {
      id: "850e8400-e29b-41d4-a716-446655440000",
      customerId: "550e8400-e29b-41d4-a716-446655440000",
      employeeId: "550e8400-e29b-41d4-a716-446655440001",
      serviceId: "650e8400-e29b-41d4-a716-446655440000",
      appointmentTime: "2024-03-18T10:00:00Z",
      createdAt: "2024-03-15T12:00:00Z",
      durationMinutes: 60,
      notes: "Example appointment",
      reminderSent: false,
      status: "scheduled"
    },
    {
      id: "850e8400-e29b-41d4-a716-446655440001",
      customerId: "550e8400-e29b-41d4-a716-446655440000",
      employeeId: "550e8400-e29b-41d4-a716-446655440001",
      serviceId: "650e8400-e29b-41d4-a716-446655440001",
      appointmentTime: "2024-03-19T14:00:00Z",
      createdAt: "2024-03-15T12:00:00Z",
      durationMinutes: 30,
      notes: "Example appointment",
      reminderSent: false,
      status: "scheduled"
    }
  ])
}